- name: Set hostname / player identifier
  script: set_hostname.sh
  changed_when: false

- name: Set up authorized_keys for the pi user
  authorized_key: user=pi key="{{ item }}"
  with_file:
    - id_rsa.pub

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart-ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart-ssh

- name: Make sure we have proper framebuffer depth
  lineinfile:
    dest: /boot/config.txt
    regexp: ^framebuffer_depth=
    line: framebuffer_depth=32

- name: Fix framebuffer bug
  lineinfile:
    dest: /boot/config.txt
    regexp: ^framebuffer_ignore_alpha=
    line: framebuffer_ignore_alpha=1

- name: Make sure we have enough GPU memory
  lineinfile:
    dest: /boot/config.txt
    regexp: ^gpu_mem=
    line: gpu_mem=128

- name: Always enable HDMI
  lineinfile:
    dest: /boot/config.txt
    regexp: ^hdmi_force_hotplug=
    line: hdmi_force_hotplug=1

- name: Set HDMI group to CEA
  lineinfile:
    dest: /boot/config.txt
    regexp: ^hdmi_group=
    line: hdmi_group=1

- name: Force HDMI mode 16 (1080p, 60 Hz)
  lineinfile:
    dest: /boot/config.txt
    regexp: ^hdmi_mode=
    line: hdmi_mode=16

- name: Hide voltage and temperature
  lineinfile:
    dest: /boot/config.txt
    regexp: ^avoid_warnings=
    line: avoid_warnings=1

- name: Backup kernel boot args
  copy:
    src: /boot/cmdline.txt
    dest: /boot/cmdline.txt.orig
    force: no

- copy:
    src: /boot/cmdline.txt.orig
    dest: /boot/cmdline.txt
    force: yes

- name: Use Systemd as init and quiet boot process
  lineinfile:
    dest: /boot/cmdline.txt
    regexp: (.*)
    backrefs: yes
    line: \1 quiet init=/lib/systemd/systemd

- name: Install Cast viewer dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - console-data
    - libffi-dev
    - libssl-dev
    - matchbox
    - omxplayer
    - python-dev
    - python-netifaces
    - python-simplejson
    - rpi-update
    - systemd
    - chromium-browser
    - x11-xserver-utils
    - xserver-xorg
    - htop
    - ufw
    - cec-utils
    - mediainfo
    - nload

- name: Perform system upgrade
  apt:
    upgrade: dist
  tags:
    - system-upgrade

- name: Perform RPI update
  command: SKIP_WARNING=1 /usr/bin/rpi-update
  tags:
    - system-upgrade

- name: Clean up unused packages
  command: apt-get -y autoremove
  tags:
    - system-upgrade

- name: Copy in rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    mode: 0755
    owner: root
    group: root

- name: Copy in 01_nodoc
  copy:
    src: 01_nodoc
    dest: /etc/dpkg/dpkg.cfg.d/01_nodoc
    mode: 0644
    owner: root
    group: root

- name: Copy in evdev
  copy:
    src: 10-evdev.conf
    dest: /usr/share/X11/xorg.conf.d/10-evdev.conf
    mode: 0644
    owner: root
    group: root

- name: Copy in monitor
  copy:
    src: 20-monitor.conf
    dest: /usr/share/X11/xorg.conf.d/20-monitor.conf
    mode: 0644
    owner: root
    group: root

- name: Clear out X11 configs (disables touchpad and other unnecessary things)
  file:
    path: "/usr/share/X11/xorg.conf.d/{{ item }}"
    state: absent
  with_items:
    - 50-synaptics.conf
    - 10-quirks.conf
    - 50-wacom.conf

- name: Restart on kernel panic
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: ^kernel.panic=
    line: kernel.panic=5

- name: Restart X
  command: /bin/true
  notify:
    - restart-x-server

- name: Disable swap
  command: /sbin/swapoff --all removes=/var/swap

- name: Remove swapfile from disk
  file:
    path: /var/swap
    state: absent
